config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  root 'uploads#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :uploadsegment
  attr_accessible :title, :author, :content, :created_at
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	attr_accessible :name, :file 
  has_many :uploadsegments, :dependent => :destroy
  has_many :articles, :through => :uploadsegments
  has_attached_file :file
  before_save :parse_file
end
  def parse_file
    tempfile = file.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end
   def parse_xml(doc)
    doc.root.elements.each do |node|
      parse_uploads(node)
    end
  end
    def parse_uploads(node)
    if node.node_name.eql? 'item'
      node.elements.each do |node|
        parse_upload_segments(node)
      end
    end
  end
  def parse_upload_segments(node)
    if node.node_name.eql? 'seg'
      tmp_segment = Uploadsegment.new
      node.elements.each do |node|
        parse_articles(node,tmp_segment)
      end
      self.uploadsegments << tmp_segment
    end
  end
   def parse_articles(node,tmp_segment)
    if node.node_name.eql? 'block'
      tmp_article = Article.new
      node.elements.each do |node|
        tmp_article.title = node.text.to_s if node.name.eql? 'title'
        tmp_article.author = node.text.to_s if node.name.eql? 'author'
        tmp_article.content = node.text.to_s if node.name.eql? 'content'
        tmp_article.created_at = node.text.to_s if node.name.eql? 'created'
      end
      tmp_segment.articles << tmp_article
    end
  end

app/models/uploadsegment.rb
class Uploadsegment < ActiveRecord::Base
  belongs_to :upload
   has_many :articles, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload=Upload.find(params[:id])
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
    @upload= Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload=Upload.find(params[:id])
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_path, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private
    def upload_params
      params.require(:upload).permit(:name, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xmlparser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-upload' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-upload' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for @upload, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :file, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :file %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                uploads_path, :class => 'btn' %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<%- model_class = Upload -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/uploads/index.html.erb
<%- model_class = Upload -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:file_file_name) %></th>
      <th><%= model_class.human_attribute_name(:file_content_type) %></th>
      <th><%= model_class.human_attribute_name(:file_file_size) %></th>
      <th><%= model_class.human_attribute_name(:file_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= link_to upload.id, upload_path(upload) %></td>
        <td><%= upload.name %></td>
        <td><%= upload.file_file_name %></td>
        <td><%= upload.file_content_type %></td>
        <td><%= upload.file_file_size %></td>
        <td><%= upload.file_updated_at %></td>
        <td><%=l upload.created_at %></td>
        <td>
             <%= link_to t('.show', :default => t("helpers.links.show")),
                      upload_path(upload), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_upload_path(upload), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      upload_path(upload),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_upload_path,
            :class => 'btn btn-primary' %>

app/views/uploads/new.html.erb
<%- model_class = Upload -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/uploads/show.html.erb
 <%- model_class = Upload -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @upload.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:file_file_name) %>:</strong></dt>
    <dd><%= @upload.file_file_name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:file_content_type) %>:</strong></dt>
    <dd><%= @upload.file_content_type %></dd>
    <dt><strong><%= model_class.human_attribute_name(:file_file_size) %>:</strong></dt>
    <dd><%= @upload.file_file_size %></dd>
    <dt><strong><%= model_class.human_attribute_name(:file_updated_at) %>:</strong></dt>
    <dd><%= @upload.file_updated_at %></dd>
  </dl>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                uploads_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_upload_path(@upload), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                upload_path(@upload),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Article Title</th>
        <th>Author</th>
        <th>Content</th>
        <th>CreationDate</th>
      </tr>
    </thead>
    <tbody>
      <% @upload.articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><%= article.author %></td>
          <td><%= article.content %></td>
          <td><%= article.created_at %></td>s
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                uploads_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_upload_path(@upload), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                upload_path(@upload),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>